import { Octokit } from 'octokit';
import { config } from '../config';

const octokit = new Octokit({
  auth: config.githubToken,
});

export interface GistResult {
  gistId: string;
  gistUrl: string;
  colabUrl: string;
  rawUrl: string;
}

/**
 * Uploads a Jupyter notebook (.ipynb) as a public GitHub Gist
 * and returns the Gist URL + Google Colab URL.
 *
 * The notebook is uploaded as a public gist so that Google Colab
 * can access it without any authentication from the user.
 */
export async function uploadNotebookToGist(
  notebookJson: string,
  filename: string
): Promise<GistResult> {
  // Ensure filename ends with .ipynb
  const safeFilename = filename.endsWith('.ipynb') ? filename : `${filename}.ipynb`;

  const response = await octokit.rest.gists.create({
    description: `Research paper implementation — generated by Better Papers`,
    public: true,
    files: {
      [safeFilename]: {
        content: notebookJson,
      },
    },
  });

  const gistId = response.data.id;
  const gistUrl = response.data.html_url;

  if (!gistId || !gistUrl) {
    throw new Error('GitHub Gist creation failed — no ID or URL returned');
  }

  // Get the raw URL for the .ipynb file (for download fallback)
  const files = response.data.files;
  const fileData = files?.[safeFilename];
  const rawUrl = fileData?.raw_url || '';

  // Construct the Colab URL: colab.research.google.com/gist/{username}/{gist_id}
  const colabUrl = `https://colab.research.google.com/gist/${config.githubUsername}/${gistId}`;

  console.log(`[Gist] Uploaded: ${gistUrl}`);
  console.log(`[Gist] Colab:    ${colabUrl}`);

  return {
    gistId,
    gistUrl,
    colabUrl,
    rawUrl,
  };
}
